### PR TITLE
Vue IONIC 4 support added

### PR DESCRIPTION
**Pull request by ghaddon**
Added Vue Ionic 4 support. All test completed successfully run using vscode F5 debug mode.

**Changed or added the following code:**

     - package.json - Added language file support for Vue 2.x

**Snippets:**

     - vue.json - cloned snippets for Vue 2.x IONIC 4.x
     - vue-html.json - cloned snippets for Vue 2.x IONIC 4.x

### CODE REVIEW

**Comment by marcjulian** [comment]
Thanks for your PR. It seems to me you just copied the snippets. 

Please review the snippets, because they contain Angular specific controls such as

* ngFor
* (click)
* [src] for input

**Comment by ghaddon** [comment]
Marc,
Your right. I was focused on the IONIC UI.
I'll review.
Thanks,Gary
    On Saturday, April 13, 2019, 12:04:43 PM MST, Marc <notifications@github.com> wrote:  
 
 
Thanks for your PR. It seems to me you just copied the snippets.

Please review the snippets, because they contain Angular specific controls such as
   
   - ngFor
   - (click)
   - [src] for input

**Comment by acyuta108** [comment]
@ghaddon sorry to [jump in front of you](https://github.com/fivethree-team/vscode-ionic-snippets/pull/23) but I figured it was easier for me to submit my own version than to try to sync efforts. I hope my fork helps all of us. Thanks for the effort anyways, it would have saved me a couple of hours converting and revising the angular->vuejs. Let me know if you find any bugs.

**Comment by ghaddon** [comment]
No problem. 
    On Wednesday, May 1, 2019, 2:34:39 PM MST, Acyuta <notifications@github.com> wrote:  
 
 
@ghaddon sorry to jump in front of you but I figured it was easier for me to submit my own version than to try to sync efforts. I hope my fork helps all of us. Thanks for the effort anyways, it would have saved me a couple of hours converting and revising the angular->vuejs. Let me know if you find any bugs.

**Pull request closed without merging**
